version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
          time: "10:00"
          timezone: "UTC"
      target-branch: "main"
      open-pull-requests-limit: 5
      assignees:
        - "deniskore"
registries:
    dockerhub:
      type: docker-registry
      url: https://registry.hub.docker.com
      username: ${{ secrets.DHUBU }}
      password: ${{ secrets.DHUBP }}
