version: "3.7"

services:
  clickhouse-server:
    image: docker.io/clickhouse/clickhouse-server:22.6.9.11-alpine
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka

  kafka:
    image: docker.io/bitnami/kafka:3.3.1
    environment:
      KAFKA_CFG_BROKER_ID: "1"
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - 9092:9092
      - 9093:9093
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "127.0.0.1:9092", "--list"]
      interval: 3s
      timeout: 3s
      retries: 3
