[workspace]
resolver = "2"

members = [
    "v1-simple",
    "v2-advanced/clickhouse-cli",
    "v2-advanced/clickhouse-scheduler",
    "v2-advanced/clickhouse-retention",
]

[profile.release]
lto = "thin"
